In [2]:
import numpy as np

In [23]:
arr1 = np.array([(1,2,3),(4,5,6),(7,8,9),(5,6,12)],dtype=np.float64)

In [24]:
arr1

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [ 5.,  6., 12.]])

In [25]:
arr1[1]

array([4., 5., 6.])

In [26]:
arr1.ndim
# show dimensions

2

In [27]:
arr2 = np.array([(111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678),
                (111.123,223.334,335.678)],dtype=np.complex128)

In [28]:
arr2

array([[111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j],
       [111.123+0.j, 223.334+0.j, 335.678+0.j]])

In [29]:
print(len(arr2))

15


In [55]:
arr2.shape

(15, 3)

In [56]:
np.mean(arr2)

(223.3783333333334+0j)

In [31]:
np.sum(arr2)

(10052.025000000001+0j)

In [32]:
np.sum(arr2[2])

(670.135+0j)

In [34]:
round(np.sum(arr2),3)

C:\Users\Admin\AppData\Local\Temp/ipykernel_9652/65915816.py:1: DeprecationWarning: The Python built-in `round` is deprecated for complex scalars, and will raise a `TypeError` in a future release. Use `np.round` or `scalar.round` instead.
  round(np.sum(arr2),3)


(10052.025+0j)

In [35]:
np.max(arr2)

(335.678+0j)

In [36]:
np.min(arr2)

(111.123+0j)

In [58]:
np.abs(arr2)

array([[111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678],
       [111.123, 223.334, 335.678]])

In [37]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [38]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [40]:
np.arange(50)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [43]:
np.arange(5,21)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [44]:
np.arange(5,21,3)

array([ 5,  8, 11, 14, 17, 20])

In [48]:
np.random.normal(55)

55.7652181999176

In [50]:
np.random.random(15)

array([0.34349292, 0.58864487, 0.17384322, 0.59294146, 0.47336412,
       0.20577905, 0.49935036, 0.99681513, 0.00509823, 0.48179116,
       0.51818418, 0.9180396 , 0.84063597, 0.86710206, 0.01260426])

In [57]:
a = np.array([3,5,4,2,1])
np.sort(a)

array([1, 2, 3, 4, 5])